name = "smart-news-translator2"
main = "src/index.ts"
compatibility_date = "2026-07-23"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "news_db"
database_id = "2815bd80-f483-4f9b-872d-93047309ed13"

[ai]
binding = "AI"

[[queues.producers]]
binding = "SCRAPE_QUEUE"
queue = "news-scrape-queue"

[[queues.producers]]
binding = "TRANSLATE_QUEUE"
queue = "news-translate-queue"

[[queues.consumers]]
queue = "news-scrape-queue"
max_batch_size = 5
max_concurrency = 2

[[queues.consumers]]
queue = "news-translate-queue"
max_batch_size = 1
max_concurrency = 1

[triggers]
crons = ["0 * * * *"]

[vars]
WP_API_URL = "https://updaaate.ir/wp-json/wp/v2/"
WP_POST_STATUS = "draft"
WP_CATEGORY_ID = "3"
TELEGRAM_CHAT_ID = "@updaaate_crypto"
